---

- name: Install required packages on Debian based systems
  ansible.builtin.apt:
    name:
      - lvm2
      - xfsprogs
      - gnupg
      - software-properties-common
    update_cache: true
    state: present

- name: Install GlusterFS
  block:
    - name: Install GlusterFS | Add GlusterFS repository
      ansible.builtin.apt_repository:
        repo: "ppa:gluster/glusterfs-{{ glusterfs_version }}"
        state: present
    - name: Install GlusterFS | Install packages
      ansible.builtin.apt:
        name:
          - glusterfs-server
        update_cache: true
        state: present

- name: Start & enable GlusterFS service
  ansible.builtin.service:
    name: glusterd.service
    state: started
    enabled: true
